---
- name: Configure machine
  hosts: localhost
  tasks:
    - name: Configure dot files
      include_role:
        name: dotfiles
    - name: Clone repos
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
      loop:
        - { repo: "https://github.com/joseph62/Scripts.git", dest: ".local/opt/Scripts" }
        - { repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git", dest: ".local/opt/zsh-syntax-highlighting" }
        - { repo: "https://github.com/ohmyzsh/ohmyzsh.git", dest: ".local/opt/ohmyzsh" }
        - { repo: "https://github.com/VundleVim/Vundle.vim.git", dest: ".vim/bundle/Vundle.vim"}
        - { repo: "https://github.com/asdf-vm/asdf.git", dest: ".asdf"}
    - name: Install packages from package manager
      ansible.builtin.package:
        name:
          - zsh
          - curl
          - htop
          - rlwrap
          - vim
          - httpie
          - jq
          - jo
          - tldr
          - watch
          - mit-scheme
          - fzf
        state: present
      become: true
      ignore_errors: true
    - name: Install rust
      include_role:
        name: rust
    - name: Install packages from pip
      ansible.builtin.pip:
        name:
          - thefuck
        state: present
    - name: Install packages from cargo
      community.general.cargo:
        name:
          - zoxide
          - fd-find
          - exa
          - ripgrep
          - bat
        state: present
    - name: Install flatpak
      include_role:
        name: flatpak
      tags:
        - gui