---
- name: Configure machine
  hosts: localhost
  roles:
    - dotfiles
    - zsh
    - rust
    - rtx
    - name: flatpak
      when: ansible_distribution != "MacOSX"
      tags: flatpak
  tasks:
    - name: Clone repos
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
      loop:
        - { repo: "https://github.com/joseph62/Scripts.git", dest: ".local/opt/Scripts" }
        - { repo: "https://github.com/VundleVim/Vundle.vim.git", dest: ".vim/bundle/Vundle.vim"}
    - name: Install general packages from package manager
      ansible.builtin.package:
        name:
          - gcc
          - curl
          - htop
          - rlwrap
          - vim
          - httpie
          - jq
          - jo
          - tldr
          - fzf
        state: present
      become: "{{ ansible_distribution != 'MacOSX' }}"
      ignore_errors: true
    - name: Install build packages for fedora
      ansible.builtin.package:
        name:
          - gcc 
          - python3-devel
          - zlib
          - zlib-devel
          - patch
          - bzip2
          - bzip2-devel
          - readline-devel
          - sqlite
          - sqlite-devel
          - openssl-devel
          - tk-devel
          - libffi-devel
          - xz-devel
          - libuuid-devel
          - gdbm-libs
          - libnsl2
        state: present
      when: ansible_distribution == 'Fedora'
      become: true
    - name: Install packages from pip
      ansible.builtin.pip:
        name:
          - thefuck
        state: present
    - name: Install packages from cargo
      community.general.cargo:
        name:
          - zoxide
          - fd-find
          - exa
          - ripgrep
          - bat
        state: present
      environment:
        PATH: "{{ lookup('env', 'HOME') }}/.cargo/bin:{{ lookup('env', 'PATH') }}"
