- name: Install zsh from package manager
  ansible.builtin.package:
    name:
      - zsh
  become: true
- name: Clone zsh repos
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
  loop:
    - { repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git", dest: ".local/opt/zsh-syntax-highlighting" }
    - { repo: "https://github.com/ohmyzsh/ohmyzsh.git", dest: ".local/opt/ohmyzsh" }
- name: Make user shell zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true