---
- name: Configure machine
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Install packages from package manager
      ansible.builtin.package:
        name:
          - zsh
          - rlwrap
          - vim
          - httpie
          - jq
          - jo
          - ripgrep
          - exa
          - bat
          - rip
          - zoxide
          - fd
          - tldr
          - watch
          - mit-scheme
          - asdf
          - thefuck
          - fzf
        state: present
      become: true
      ignore_errors: true
    - name: Clone repos
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
      loop:
        - { repo: "https://github.com/joseph62/dot-files.git", dest: ".local/etc/dot-files" }
        - { repo: "https://github.com/joseph62/Scripts.git", dest: ".local/opt/Scripts" }
        - { repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git", dest: ".local/opt/zsh-syntax-highlighting" }
        - { repo: "https://github.com/ohmyzsh/ohmyzsh.git", dest: ".local/opt/ohmyzsh" }
        - { repo: "https://github.com/VundleVim/Vundle.vim.git", dest: ".vim/bundle/Vundle.vim"}
    - name: Symlink rc files
      ansible.builtin.file:
        src: "{{ lookup('env', 'HOME') }}/.local/etc/dot-files/{{ item }}"
        dest: "{{ lookup('env', 'HOME') }}/.{{ item }}"
        state: link
      loop:
        - zshrc
        - bashrc
        - vimrc
        - gitconfig
        - profile
        - bash_logout
    - name: Make home directories
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/{{ item }}"
      loop:
        - Projects
        - Downloads
    - name: Download rustup install script
      register: cargo_installer_downloaded
      ansible.builtin.get_url:
        dest: "{{ lookup('env', 'HOME') }}/Downloads/rustup_install.sh"
        url: https://sh.rustup.rs
        mode: "0777"
    - name: Invoke rustup install script
      changed_when: cargo_installer_downloaded
      ansible.builtin.command:
        argv:
          - "{{ lookup('env', 'HOME') }}/Downloads/rustup_install.sh"
          - "-y"
